-- LOTE 1: DEFINIÇÕES E VÍDEOS

INSERT INTO public.system_settings (id, key, value, updated_at) VALUES ('cbb0d8d0-3d5f-4c5a-99c7-c12bbf677051', 'ticker', '{"speed":30}', '2026-03-24T00:20:06.57795+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.breaking_news (id, text, active, created_at) VALUES ('60f13c07-e5e9-477b-b69c-e1e57cd60a8f', 'RDCongo – violação do cessar-fogo - Conflitos complexos exigem cautela na interpretação de notícias. Informações oficiais e verificadas devem orientar a compreensão dos acontecimentos no leste da RDCongo.', true, '2026-02-25T01:37:13.552747+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.breaking_news (id, text, active, created_at) VALUES ('b6ac1a97-51a7-4212-836b-0bc4e64a0e82', 'Bodo/Glimt choca Milão: O Bodo/Glimt confirma que, mesmo fora dos grandes centros do futebol europeu, estratégia e eficácia podem derrubar favoritos. Acompanhe os próximos confrontos e verifique sempre resultados oficiais antes de compartilhar notícias de desporto.', true, '2026-02-25T01:37:55.053943+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.breaking_news (id, text, active, created_at) VALUES ('f99d3c70-e43c-447a-918b-70ef21d5c5de', 'Falsos CAPTCHA: Mesmo elementos familiares da internet podem ser armadilhas. Sempre verifique URLs e instruções antes de seguir comandos. A segurança online depende da atenção de cada utilizador.', true, '2026-02-25T01:38:19.707564+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.breaking_news (id, text, active, created_at) VALUES ('fa5e5bd1-5331-415e-a357-ec31f0d35200', 'Sociedade: Os números do INE refletem apenas a população residente e são fundamentais para planeamento urbano e políticas públicas. Crescimento rápido das cidades exige atenção à infraestrutura, habitação e serviços básicos.', true, '2026-02-25T02:12:39.782097+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.breaking_news (id, text, active, created_at) VALUES ('f9142d9d-8e93-49fa-99dd-c9cf0c31db0d', 'A condecoração de hoje reforça o reconhecimento institucional pelos serviços prestados à segurança pública em Angola, especialmente no quadro das comemorações dos 50 anos da Polícia Nacional. O gesto tem peso simbólico para a corporação e para a promoção da carreira policial, num contexto em que segurança interna continua no centro da agenda pública.', true, '2026-02-25T07:30:17.502383+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.opinion_articles (id, title, author, avatar_url, excerpt, content, published, created_at, updated_at) VALUES ('4cbefbbb-fd70-4c8a-8562-a3d8d3b7bea0', 'Questões profundas sobre o estado da liberdade de imprensa e da protecção de dados em Angola.', 'Álvaro Muenhu Yanga Xito', 'https://pstzibmplwiatkuanhhn.supabase.co/storage/v1/object/public/news/3fqzv2bxer5_1771690709359.jpg', 'O alegado caso de espionagem denunciado pela UNITA contra o jornalista Teixeira Cândido evidencia riscos sérios para a liberdade de imprensa em Angola. Mais do que identificar culpados de imediato, torna-se essencial garantir uma investigação independente, transparente e credível, capaz de proteger jornalistas e reforçar a confiança nas instituições.', 'Na minha opinião, independentemente de quem esteja por trás da eventual vigilância, o simples facto de existir suspeita credível de uso de spyware contra um jornalista é preocupante. Jornalistas desempenham um papel essencial numa democracia: fiscalizar o poder, expor irregularidades e garantir que a sociedade tenha acesso à informação. Quando há sinais de vigilância digital, cria-se um clima de intimidação que pode afectar não apenas um profissional, mas toda a classe.

Outro ponto crítico é a transparência institucional. Casos desta natureza exigem investigações rápidas, técnicas e independentes. Sem esclarecimento público, aumentam a desconfiança nas instituições e fortalece-se a percepção de que ferramentas tecnológicas podem estar a ser usadas para fins políticos.

Também é importante evitar conclusões precipitadas. A gravidade do tema exige provas sólidas, perícia forense credível e respeito pelo devido processo legal. Defender a liberdade de imprensa não significa assumir culpados antes da investigação — significa garantir que a verdade seja apurada.

Em síntese, este caso deve servir como alerta: Angola precisa reforçar mecanismos legais e técnicos de protecção contra vigilância abusiva, criar regras claras para o uso de tecnologias de intercepção e assegurar que jornalistas possam trabalhar sem medo. A forma como este episódio for investigado e esclarecido terá impacto directo na confiança pública e na qualidade da democracia.', true, '2026-02-21T16:18:34.386569+00:00', '2026-02-21T16:18:34.386569+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.opinion_articles (id, title, author, avatar_url, excerpt, content, published, created_at, updated_at) VALUES ('56ffd82b-159c-4774-be84-c36de7f323a8', 'Economia de Angola: entre sinais de recuperação e desafios estruturais persistentes', 'Cláudio Segunda | Produtor de conteúdos | Economista | Mestrando em Finanças Públicas | Consultor financeiro', 'https://pstzibmplwiatkuanhhn.supabase.co/storage/v1/object/public/news/b9akkb5iz5_1772046860217.jpeg', 'A economia de Angola vive hoje um momento de transição delicada. Nos últimos anos, registaram-se sinais claros de recuperação macroeconómica, impulsionados sobretudo pela estabilização cambial, maior disciplina fiscal e algum controlo da inflação. No entanto, estes avanços continuam longe de se traduzir em melhorias consistentes no dia a dia da maioria dos cidadãos.', 'A forte dependência do petróleo permanece como o principal calcanhar de Aquiles do país. Sempre que o preço do crude sobe, a economia respira; quando cai, o impacto sente-se de forma quase imediata nas contas públicas, no investimento e no emprego. Apesar do discurso recorrente sobre diversificação económica, os resultados práticos ainda são limitados. Agricultura, indústria transformadora e turismo continuam subaproveitados face ao potencial real que o país possui.

Outro ponto crítico é o custo de vida. Mesmo com alguma desaceleração da inflação, os preços dos bens essenciais permanecem elevados, pressionando famílias de rendimentos baixos e médios. O crescimento económico, quando existe, é muitas vezes percebido como distante, técnico e concentrado em indicadores macro, sem reflexo direto no poder de compra ou na criação de emprego sustentável.

Há também um desafio estrutural ligado ao ambiente de negócios. Embora reformas tenham sido anunciadas para atrair investimento privado e estrangeiro, persistem entraves como burocracia excessiva, dificuldades no acesso ao crédito e insegurança jurídica percebida por empresários nacionais e internacionais. Sem um setor privado forte, dinâmico e confiante, a economia dificilmente ganhará tração de longo prazo.

Por outro lado, é justo reconhecer avanços. A maior transparência nas contas públicas, o esforço de consolidação fiscal e a aposta gradual na digitalização de serviços do Estado representam passos na direção certa. O desafio está em garantir que estas reformas não fiquem confinadas aos relatórios oficiais, mas tenham impacto real na produção, no emprego e na renda das famílias.

Em síntese, a economia angolana encontra-se num ponto intermédio: já não está na crise profunda de anos anteriores, mas ainda longe de um crescimento inclusivo e sustentável. O futuro dependerá menos de choques externos favoráveis e mais da capacidade interna de diversificar a economia, fortalecer instituições e colocar o cidadão no centro das políticas económicas. Sem isso, a recuperação continuará a ser estatística — e não social.', true, '2026-02-25T19:14:22.090439+00:00', '2026-02-25T19:14:22.090439+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.opinion_articles (id, title, author, avatar_url, excerpt, content, published, created_at, updated_at) VALUES ('1f6c0ebc-889d-4901-8c24-3438b11bf9bb', 'Guerra no Médio Oriente: oportunidades e riscos para África e Angola', 'Ivan Lima', 'https://www.giranoticias.com/_midias/jpg/2023/10/24/foto_ivam_lima-348203.jpg', 'A escalada do conflito no Médio Oriente, com ataques iranianos contra bases dos EUA e retaliações em Israel e países do Golfo, não é um fenómeno isolado. Embora distante geograficamente de África, os efeitos desta guerra chegam ao continente de forma directa e indirecta, afectando economias, segurança e política internacional.', 'Vantagens potenciais para África e Angola:

Preços do petróleo e energia: Angola, enquanto produtor de petróleo, pode beneficiar de aumentos nos preços internacionais de crude provocados pela instabilidade no Golfo. Esse efeito pode gerar receitas extras para o Orçamento Geral do Estado, desde que o país consiga manter a produção estável.

Revisão de alianças diplomáticas: Conflitos de grande escala geram uma redistribuição do poder internacional. Angola pode aproveitar o momento para reforçar relações com países fora da órbita directa dos EUA e do Irã, diversificando parcerias económicas e estratégicas.

Investimentos em segurança e defesa: A percepção global de instabilidade tende a aumentar o interesse por cooperação em segurança. Angola pode negociar transferências de tecnologia militar e capacitação das suas forças armadas, fortalecendo a soberania nacional.

Desvantagens e riscos significativos:

Volatilidade económica: A alta nos preços do petróleo pode gerar lucros temporários, mas também aumenta o custo de bens importados e afecta a inflação local. Angola, com a sua economia ainda dependente de importações, pode sofrer impactos directos no custo de vida da população.

Instabilidade geopolítica global: A guerra no Médio Oriente pode criar crises alimentares e financeiras internacionais, afectando África. Países como Angola, que importam cereais e outros produtos estratégicos, podem enfrentar escassez ou aumento de preços.

Risco de envolvimento indirecto: Embora Angola não esteja directamente envolvida, pressões políticas internacionais podem exigir posicionamentos ou alianças que limitam a autonomia do país. Além disso, empresas e cidadãos angolanos no exterior podem ser afectados por evacuações e insegurança.

Conclusão:
Para Angola, a guerra no Médio Oriente é um alerta sobre a vulnerabilidade global das economias africanas. É uma oportunidade para reforçar a diplomacia, diversificar parceiros e proteger sectores estratégicos, mas também é um risco concreto para a estabilidade económica e social do país. A chave será equilíbrio: aproveitar os efeitos positivos de curto prazo sem se expor às consequências negativas da escalada militar global.', true, '2026-03-02T14:01:12.822165+00:00', '2026-03-02T14:01:12.822165+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('08ba738f-77a0-4acd-9f42-fb6fe24d8b40', 'México fica às escuras! Forças Especiais derrubam chefão do cartel', 'México fica às escuras! Forças Especiais derrubam chefão do cartel', 'https://www.youtube.com/watch?v=5hGixxn336U', 'https://i.ytimg.com/vi/5hGixxn336U/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAKVNQb0PikTctR7taUEAZVWpltyw', '15:59', 'Vídeo', 7233, true, '2026-02-24T18:10:26.821977+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('5f9526bd-c897-493f-91df-f5859ea7c901', 'Guerra no Oriente Médio: vídeo mostra míssil iraniano atingindo base dos EUA no Bahrein', 'Um vídeo divulgado neste sábado, 28, mostra o exato momento em que um míssil lançado pelo Irã atingiu uma instalação da Marinha dos Estados Unidos no Bahrein. O ataque é parte da retaliação da Guarda Revolucionária Iraniana aos recentes ataques coordenados de Israel.

Bases militares norte-americanas no Golfo têm sido alvo de ataques iranianos desde o início da ofensiva dos EUA na região. Mais cedo, o ex-presidente Donald Trump justificou a ação, afirmando que o Irã “nunca poderá ter armas nucleares”, após múltiplas rodadas de negociações frustradas.

A escalada do conflito aumenta significativamente a tensão no Médio Oriente, com riscos crescentes para a estabilidade regional e global.', 'https://www.youtube.com/watch?v=nAGyiRTEBOE', 'https://www.estadao.com.br/resizer/v2/5D3FVBAP55DVDDRFNFZZVD7X5Y.png?quality=80&auth=50ae790b2d1241d836ac7e04eebcf3cf14301a07b6d76b4d8f3871a76344dfea&width=1200&height=675&smart=true', '0:55', 'Vídeo', 5644, true, '2026-03-02T13:48:27.41478+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('16201738-a329-4c1a-b79a-821ccb825e06', 'Novo líder do Irã promete endurecer confronto e desafiar presença dos EUA no Oriente Médio', 'Em entrevista, o líder religioso Hossein Khaliloo comentou a escolha do sucessor de Ali Khamenei pela Assembleia de Especialistas. Segundo ele, o novo líder é jovem, próximo da Guarda Revolucionária Islâmica e deve manter a linha dura contra Estados Unidos e aliados. Khaliloo afirmou que a morte do antigo líder não enfraqueceu o regime e que o apoio popular fortalece a revolução iraniana. Ele também disse que a resistência regional tende a se intensificar no Oriente Médio. Sobre armas nucleares, afirmou que o uso é proibido pela doutrina islâmica, mas a decisão sobre desenvolver esse tipo de tecnologia dependerá do novo líder', 'https://youtu.be/dWe6UorWhXg?t=55', 'https://cdn.crusoe.com.br/uploads/2026/03/capa-noticia-2133x1200-4-2-1024x576.jpg', '8:51', 'Vídeo', 3926, true, '2026-03-09T19:34:12.581591+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('dfd81621-5ba7-4d4e-b36e-b17f973a287d', 'PROCESSO DE EXPULSÃO DO VALDIR DO MPLA ESTÁ VAIADO DE VÍCIOS, É INCONSTITUCIONAL', 'A controvérsia em torno da expulsão de Valdir ganhou força após surgirem alegações de que o procedimento foi conduzido sem respeito pelas regras estatutárias e pelos direitos fundamentais do militante. Entre os principais pontos levantados estão a ausência de contraditório efetivo, falhas na notificação, prazos irregulares e decisões tomadas por instâncias cuja competência é questionada.

Juristas ouvidos informalmente apontam que, a confirmar-se, tais falhas configuram vícios insanáveis, capazes de tornar o ato nulo. Para além do plano interno do partido, o caso levanta dúvidas de compatibilidade com a Constituição, sobretudo no que toca ao direito de defesa, à legalidade dos atos e à proporcionalidade das sanções.

No plano político, críticos argumentam que o processo reflete uma tendência de centralização disciplinar e de punição exemplar, enquanto defensores da decisão sustentam a necessidade de preservar a coesão e a disciplina partidária. O choque entre estas leituras expõe uma tensão antiga: até onde vai a autonomia partidária e onde começam os limites impostos pelo Estado de Direito?

Sem um esclarecimento público detalhado sobre os fundamentos, a instrução e a legalidade do processo, a decisão corre o risco de fragilizar a credibilidade interna e de abrir precedentes perigosos. A questão central permanece: disciplina pode justificar atropelos procedimentais?

Sem filtros, o caso de Valdir coloca o MPLA perante um teste sensível — não apenas político, mas também jurídico — num momento em que a exigência por transparência e respeito às regras é cada vez maior.', 'https://www.youtube.com/watch?v=e2DNuPwHL0I', 'https://i.ytimg.com/vi/B6edaTHuTFk/hqdefault.jpg', '6:45', 'Vídeo', 7089, true, '2026-02-23T21:14:48.608966+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('88c38c33-10bb-4670-b809-242cd95e7cf9', 'CUBA VAI CAIR? Trump ''antecipa'' fim do comunismo na ilha caribenha: ''Muito em breve''', 'O presidente dos EUA, Donald Trump, afirmou recentemente que o governo comunista de Cuba pode “cair muito em breve”, mas isso é uma previsão política dele, não significa que o regime vá realmente acabar imediatamente.

O que Trump disse

Trump declarou em entrevista que “Cuba vai cair muito em breve” e que o governo cubano estaria interessado em negociar com os EUA.

Ele disse que pretende colocar o secretário de Estado Marco Rubio para conduzir possíveis negociações.

Segundo Trump, o regime estaria fraco por causa da crise econômica e da pressão internacional.

O que está acontecendo em Cuba agora

Há realmente uma crise forte na ilha:

Falta de combustível e apagões de energia.

Escassez de comida, medicamentos e combustível.

Pressão dos EUA com sanções e bloqueio de petróleo.

Essa situação aumentou depois que os EUA cortaram fontes de petróleo que vinham principalmente da Venezuela.

Mas o comunismo vai acabar mesmo?

Ninguém sabe. Existem três cenários possíveis:

1️⃣ Negociação com os EUA e reformas económicas (tipo Vietname ou China).
2️⃣ Mudança política interna se a crise piorar e houver grandes protestos.
3️⃣ O regime continuar, como já aconteceu muitas vezes nas últimas décadas.

Cuba é governada pelo Partido Comunista desde a revolução liderada por Fidel Castro em 1959, e já resistiu a várias crises e pressões externas.

✅ Conclusão:
Trump acredita que o regime pode cair em breve, mas isso é uma previsão política. A realidade é que Cuba está numa crise grave, mas não há confirmação de que o comunismo vá acabar imediatamente.', 'https://www.youtube.com/watch?v=cLkMiZnm7qc', 'https://i.ytimg.com/vi/cLkMiZnm7qc/maxresdefault.jpg', '8:46', 'Vídeo', 3777, true, '2026-03-09T19:54:52.40999+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('4d4f68db-e765-41d1-a5f9-e280190cafd5', 'Cortes Milionários no Parlamento (Estratégia ou Crise?)', 'O governo decidiu reduzir despesas ligadas ao parlamento, incluindo benefícios, viagens e custos institucionais. Mas o verdadeiro debate vai além da política: o que estes cortes revelam sobre a economia do país?
Neste vídeo fazemos uma análise clara e objetiva para entender se estamos perante uma medida de responsabilidade financeira ou um sinal de pressão económica mais profunda.
📊 Neste vídeo você vai entender:
✅ por que governos fazem cortes orçamentais
✅ o impacto dos cortes públicos na economia nacional
✅ como decisões políticas influenciam empresas e cidadãos
✅ o que investidores observam quando o Estado reduz despesas
✅ possíveis consequências económicas nos próximos anos
Este conteúdo é educativo e focado em economia, finanças públicas e análise política, ajudando a compreender os sinais económicos que muitas vezes passam despercebidos nas notícias.

👉 Na sua opinião: estes cortes mostram controlo financeiro ou indicam dificuldades económicas? Deixe o seu comentário.', 'https://www.youtube.com/watch?v=Le-zmoH9fuQ', 'https://www.cedesa.pt/wp-content/uploads/2021/03/revisao-constitucional.jpg', '10:16', 'Vídeo', 6857, true, '2026-02-26T18:09:09.767345+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('5ffa1038-cedb-4746-9ce8-853d97e7c1a1', 'Espionagem ao jornalista angolano Teixeira Candido levanta questões sobre liberdade de imprensa', 'O aparelho terá sido infectado depois de Teixeira Candido ter clicado num link enviado através do WhatsApp, permitindo aos responsáveis pelo ataque acesso completo ao conteúdo do seu telemóvel. Este é considerado o primeiro caso confirmado do uso do spyware Predator em Angola.

Para analisar este caso e os riscos que representa para os jornalistas em Angola, recebemos hoje o próprio Teixeira Candido.', 'https://youtu.be/O-47YNZeIc0', 'https://pstzibmplwiatkuanhhn.supabase.co/storage/v1/object/public/news/s1d3ytcqic_1771691838072.jpg', '10:19', 'Vídeo', 7185, true, '2026-02-21T16:37:25.804725+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('35ca0c1f-12a9-42c7-8ffc-cb11a5a11207', 'Implacável! Como os EUA Executaram a Operação que Eliminou ALI KHAMENEI', 'Este vídeo analisa detalhadamente a queda do regime de Khamenei no Irã e os eventos militares e geopolíticos que levaram à operação de 28 de fevereiro de 2026. Entenda os bastidores da inteligência que localizou o Líder Supremo e as consequências econômicas imediatas para o mundo.', 'https://www.youtube.com/watch?v=GJQz7jFChCU', 'https://i.ytimg.com/vi/jZpzXq7eXi4/maxresdefault.jpg', '15:02', 'Vídeo', 5230, true, '2026-03-04T19:30:00.654145+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('7245513c-9c9a-4358-b23f-36cffeb8160a', 'A LEI É PARA SER CUMPRIDA, ELA NÃO É DECORATIVA. TC FAÇA JUSTIÇA', 'A lei existe para ser cumprida. Não é ornamento institucional, nem instrumento seletivo aplicado conforme conveniências políticas. Quando decisões são tomadas à margem dos procedimentos legais, o problema deixa de ser apenas interno e passa a ser estrutural.

Nos últimos dias, crescem as vozes que defendem que o Tribunal Constitucional deve intervir para repor a legalidade, face a processos contestados por vícios graves, atropelos ao direito de defesa e possíveis violações constitucionais. Para muitos juristas e observadores, o silêncio ou a inação judicial apenas reforçam a perceção de impunidade.

Num Estado de Direito, a justiça não pode funcionar como extensão de interesses partidários. A Constituição impõe limites claros, inclusive às organizações políticas, e exige que qualquer sanção respeite princípios como legalidade, proporcionalidade e contraditório. Quando estes pilares são ignorados, a justiça deixa de ser justiça — transforma-se em formalidade vazia.

O momento é decisivo. Ao Tribunal Constitucional cabe demonstrar que a lei vale para todos, sem exceção, e que o poder encontra travão na norma jurídica. Não se trata de proteger indivíduos ou estruturas, mas de preservar a credibilidade do próprio sistema.

Sem filtros, a exigência é simples e direta: a lei não é decorativa. Cabe ao Tribunal Constitucional fazer justiça — ou assumir o peso da omissão.', 'https://www.youtube.com/watch?v=nU0jS31cznc', 'https://i.ytimg.com/vi/nU0jS31cznc/sddefault.jpg', '6:16', 'Vídeo', 7144, true, '2026-02-23T21:17:06.337884+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('54bfee36-426c-4136-aff8-a74b9c8ae3a0', 'CARLOS CABAÇA HUMILHA MÁRIO ARAGÃO APÓS O MESMO TENTAR DEFENDER JOÃO LOURENÇO', 'O momento ocorreu num debate acalorado, onde Aragão procurou defender políticas e ações atribuídas ao chefe de Estado, tentando contextualizar algumas medidas que têm gerado críticas na sociedade. Cabaça, conhecido pelo seu estilo incisivo, não poupou comentários, evidenciando falhas nos argumentos apresentados e questionando a coerência das justificativas.

O confronto, além de pessoal, reflete tensões mais amplas dentro do cenário político, com figuras de destaque a debater não apenas políticas públicas, mas também legitimidade, lealdade partidária e eficácia das decisões governamentais. Para observadores, o episódio é um reflexo da dificuldade de conciliar defesa de lideranças com análise crítica e independente.

Sem filtros, a cena serve como um alerta: mesmo dentro de estruturas partidárias e de governo, o espaço para confrontos diretos e transparentes existe, e a capacidade de argumentar é testada constantemente — especialmente quando se toca em temas sensíveis ligados ao poder e à reputação do Presidente da República.', 'https://www.youtube.com/watch?v=yjuRvkNe7Es', 'https://i.ytimg.com/vi/yjuRvkNe7Es/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDCc30Zdoqkr62A-6td-S-0l12n5Q', '19:58', 'Vídeo', 7042, true, '2026-02-23T21:19:33.834292+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('86739920-1ff9-4c87-a5fa-e40f7b304dfc', 'PRINCIPAIS DESTAQUES NOTICIOSOS DE 25 DE FEVEREIRO DE 2026 (CIPRA)', 'Visite o Canal oficial do CIPRA (Centro de Imprensa da Presidência da República de Angola)', 'https://www.youtube.com/watch?v=tty5RBxBojk', 'https://i.ytimg.com/vi/R_WHU0LEeV8/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGEkgUihlMA8=&rs=AOn4CLDQ5IK6ruGQckolyFa1qVts5oEyFg', '4:58', 'Vídeo', 6737, true, '2026-02-26T18:16:06.642883+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('22d8793c-183c-49f6-bd28-c2f8b8366f36', 'CNN BRASIL', 'Assista AO VIVO ao CNN 360° desta quarta-feira, 04 de março de 2026. #CNNBrasil', 'https://www.youtube.com/watch?v=Qumafxs_gAE', 'https://i.ytimg.com/vi/2p8_Lo4ZvIk/maxresdefault.jpg', '00:00', 'Vídeo', 5188, true, '2026-03-04T19:46:12.81399+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('28185966-6120-423f-b649-9a364ece9b53', 'O discurso do novo Presidente na íntegra "Trago-vos uma palavra de esperança: acreditem em Portugal".', 'António José Seguro já tomou posse como Presidente da República. No Parlamento, o sucessor de Marcelo Rebelo de Sousa falou da nova ordem mundial e do desrespeito pelo direito internacional, apresentando a Europa como solução. Exigiu compromissos entre partidos para que país seja "viável" e prometeu ser o "Presidente de Portugal inteiro." E deixou uma mensagem: "acreditem em Portugal".', 'https://www.youtube.com/watch?v=S5QHjYRfAPo', 'https://c2a.portais.gov.ao/uploads/large_6272294_imagem_efaa98103f.jpeg', '24:11', 'Vídeo', 3665, true, '2026-03-10T08:04:46.305009+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.video_news (id, title, description, video_url, thumbnail_url, duration, category, views, published, created_at, updated_at) VALUES ('8efe9327-9d56-4288-9b31-de40111abe44', 'Preocupação do FMI com a dívida na África Subsaariana', 'O FMI e as próprias autoridades africanas têm repetidamente destacado que uma grande parte dos países da África Subsaariana enfrenta níveis elevados de dívida pública, que limitam a capacidade de financiamento de serviços essenciais e investimentos produtivos. De facto, um relatório recente do próprio Fundo mostra que vários países da região estão em risco elevado de incumprimento ou já em dificuldade de pagamento devido à elevada dívida acumulada, resultado de choques sucessivos (pandemia, choques de preços, fraca receita fiscal e custos de financiamento altos).

Georgieva: “Reduzir dívida é fundamental para crescimento sustentável”

Em diversas intervenções públicas — incluindo encontros com governos e sociedade civil — Kristalina Georgieva tem sublinhado que níveis elevados de dívida estagnam o crescimento económico e reduzem o espaço fiscal para responder a choques ou financiar prioridades sociais como saúde, educação e infra-estruturas. Ela tem apelado a que os países implementem reformas para reduzir a dívida e reforçar a resiliência económica.', 'https://hlsvod.dw.com/i/Events/mp4/vdt_pt/2020/bpor200219_006_kristalina_01g_,sd,hd,.mp4.csmil/master.m3u8', 'https://www.diariopopular.com.ar/mrf4u/statics/i/ps/media.diariopopular.com.ar/p/5e8c6c43ff88ba90f5d46ed40a09203d/adjuntos/143/imagenes/008/187/0008187961/1140x0/smart/kristalina-georgieva-fmi-argentina.jpg', '1:28', 'Vídeo', 7143, true, '2026-02-24T11:57:48.861191+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
