-- PARTE 3: NOTÍCIAS (LOTE 2)

INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('db6549bf-92ff-44d3-9ab2-3c3ca3cc42a4', 'Denúncia interna no MPLA aponta irregularidades no alargamento do Comité Nacional da OMA', 'Quadros do MPLA tornaram público um protesto interno no qual denunciam alegadas irregularidades no processo de alargamento do Comité Nacional da OMA, acusando responsáveis partidários de desrespeitarem orientações superiores e favorecerem determinadas figuras ligadas ao partido.', 'alegam que foram integrados 58 novos membros, quando o previsto seria apenas a inclusão de cerca de 14 adicionais.

O documento refere ainda que entre os novos nomes constariam esposas de generais e familiares de figuras influentes do partido, levantando suspeitas de critérios de favorecimento. Os denunciantes apontam também a inclusão de quadros sem trajectória política conhecida na OMA, bem como a nomeação de Zayda Payama para o Gabinete da Vice-Presidente da organização, alegadamente sem percurso relevante na estrutura feminina do MPLA.

Ponto de vista — Sem Filtros:
As denúncias revelam que as disputas internas no MPLA continuam longe de terminar. Quando estruturas partidárias são acusadas de favorecer círculos familiares e interesses de bastidores, o debate deixa de ser apenas político e passa a ser sobre credibilidade institucional — algo que o partido no poder dificilmente pode ignorar.', 'Política', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh_qpyZLtPBZ8NIxHQ_uSPeIdoX3z_h5zpjZOkUGmr40a86uS0iG4L6j9DsqgrDfi-baqIIimtVsJF30n1Q-rMag6C3LtOBk2_idlrlEzBzvwDR8VOUPMYPIvVeNlbAkhKws-21aRivYkbK02rKW4Lh5qgeZi4hr5-rM2dQiLdtz37iEuYBUG8kBhTU0_yV/s1329/IMG_2683.jpeg', 'Redacção', false, true, true, 4965, '2026-03-05T10:53:52.523101+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('ae279751-25cd-491d-a54b-f6ab2226cc0c', 'Quando Desporto e Rock Colidem: O Lado Inusitado de Rodman', 'Por trás da aparência excêntrica, do cabelo pintado e das unhas arranjadas, o lendário basquetebolista Dennis Rodman sempre escondeu uma profunda luta interna, caos e dor. Numa recente conversa com Joe Buck, o famoso atleta revelou como a música da banda Pearl Jam ajudou a salvar-lhe a vida num dos momentos mais difíceis', 'A crise instalou-se em 1992. Depois de Chuck Daly, o treinador dos Detroit Pistons que Rodman via como uma figura paterna, ter deixado a equipa, o seu mundo desmoronou-se. Ao mesmo tempo, passava por um divórcio difícil com a sua esposa, Annie Bakes, enquanto os meios de comunicação social o criticavam incessantemente.

«Tudo estava a desmoronar-se. Fechei-me em casa durante 45 dias. Não queria falar com ninguém», recorda Rodman.
A ajuda dos Pearl Jam
Uma noite, estava sentado na sua carrinha, em frente ao pavilhão dos Pistons, com uma pistola carregada, enquanto a música Black dos Pearl Jam, que fora lançada no ano anterior, tocava no rádio.

A polícia encontrou-o horas mais tarde a dormir no veículo, com a música ainda a tocar. Rodman explicou que a sua intenção não era «matar o Dennis», mas sim libertar-se do que se tinha tornado – um homem quebrado e perdido que não sabia a que lugar pertencia. «Eu só queria mudar a minha vida», disse a antiga figura da NBA.

A transformação
Pouco depois, foi trocado para os San Antonio Spurs, onde a sua transformação começou. Começou a mudar a sua aparência, a pintar o cabelo e a usar roupas provocadoras, saias e maquilhagem. Essa reviravolta, segundo ele, marcou o seu novo começo.

«Comecei a matar o meu antigo eu e a viver como alguém novo», explicou.

Hoje, aos 63 anos, Rodman fala abertamente sobre os demónios com os quais ainda luta, mas também sobre a gratidão por ter sobrevivido a momentos difíceis: «As pessoas apostavam que eu morreria antes dos 40. E aqui estou eu, ainda vivo. Veem-me como um tipo selvagem e louco, mas sei que fiz muitas coisas boas neste planeta. Só que ninguém quer ver isso.»

Rodman ''apaga'' LeBron
O norte-americano também falou sobre quem é o melhor basquetebolista de todos os tempos e mantém a firme convicção de que é o seu antigo colega de equipa. Rodman e Michael Jordan jogaram juntos nos Chicago Bulls durante três anos, durante os quais conquistaram três anéis de campeão e ficaram na memória como parte da melhor equipa da história do basquetebol.

«Já viram Michael Jordan a simular faltas? É tudo o que tenho a dizer. Basquetebol não é sobre quanto tempo se joga, mas sim sobre quão alto o seu jogo atinge quando é mais necessário. Longevidade não é grandeza, o auge é grandeza. Mike é grandeza e ninguém o vai tocar. LeBron usou o número 23 por quase 20 anos e não aprendeu o que isso significa. Apenas os seus fãs, ao vê-lo perder em finais, o tornam maior do que ganhar seis campeonatos. De onde eu venho, isso chama-se delírio, não legado. Sempre que as coisas ficam difíceis, LeBron faz as malas, chama estrelas e forma uma nova super-equipa. Mike não foi para outra equipa, não se escondeu, não chorou. Jordan apanhava pancada de Detroit, Boston e ficava mais forte. LeBron apanha uma pancada e procura a câmara mais próxima. Se me disserem que LeBron é melhor, então não estão a ver basquetebol, estão a ver os resumos», atirou.

Dennis Rodman ficou na memória como um dos maiores excêntricos da história do basquetebol. Jogou em Detroit, Dallas, San Antonio, Chicago, Los Angeles, e conquistou cinco anéis e dois prémios de Melhor Defensor do Ano. É um dos melhores jogadores de sempre nos ressaltos e, desde 2011, membro do Hall of Fame da NBA.', 'Mundo', 'https://thumbs.web.sapo.io/?H=640&W=1280&crop=center&delay_optim=1&epic=V2%3AJhDqn0VMU4sP5UddVNhbixUDolERZfov0FBHE6tgJslQ5bmLaMr7v0cc8SNNk2FGgFJN37e915g91qtZr3ngcI1clM%2B6yRGWpz3cVckW3oVFzC59OQHvGiCE8E7W3JG5rGNRs9x4jCcyYRWkIpuenv%2FEX8ytzmugutadwAmi65yRE1iFpQFgPTg3W9jJwJD9gQRxeRaN%2BJAPsQCKckGgY16jgI6OUv2UUVZpW%2BlebFzx%2FZeT%2Bh0FWzNivf3r7Bfe&webp=1&Q=80&tv=1', 'Redacção', true, true, true, 7158, '2026-02-23T20:34:36.781579+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('bd6d5cd1-21ec-4a16-ae8a-a18b9dca0a2b', 'Angola brilha na ITB Berlim 2026, exibindo diversidade cultural e maravilhas naturais', 'A ITB Berlin 2026 começou a 2 de Março com destaque especial para Angola, país anfitrião desta edição histórica do 60º aniversário do evento. Angola apresentou ao mundo a sua cultura vibrante e as belezas naturais do território, com uma cerimónia de abertura que reuniu mais de 700 convidados VIP. Este ano, a feira foi dedicada ao tema “O Ritmo da Vida”, refletindo a oferta turística única do país e projetando a sua imagem internacional.', 'Celebrações culturais e participação de alto nível
A cerimónia de abertura proporcionou um espectáculo visual e sonoro que capturou a essência angolana. O programa cultural Travessia – Do Tradicional ao Moderno levou os convidados numa viagem pela música e dança angolanas, do semba, rebita e rumba até interpretações contemporâneas. A presença de figuras internacionais, incluindo o prefeito de Berlim, Dr. Christopher Ploss, e o presidente do Conselho Mundial de Viagens e Turismo (WTTC), reforçou a importância da estreia de Angola no turismo global.

Angola como destino turístico emergente
Para mostrar as potencialidades do país, Angola organizou um evento focado nas suas maravilhas naturais, incluindo as Cataratas de Kalandula e o Deserto da Namíbia, acompanhado de tecnologia avançada e exposições culturais que destacaram a flora e fauna locais. O ecoturismo e o turismo de aventura foram enfatizados, criando novas oportunidades para operadores e especialistas do sector turístico.

Com o slogan “Visite Angola – O Ritmo da Vida”, o país apresenta-se como uma nação vibrante, oferecendo experiências únicas aos visitantes. Angola alia autenticidade cultural e sustentabilidade, apostando num turismo responsável e adaptado às tendências globais.

Perspectivas para o futuro
A participação de Angola na ITB Berlin 2026 consolida o país como um destino turístico em ascensão. Analistas e operadores internacionais demonstraram grande interesse no sector turístico angolano, reconhecendo o potencial do país para atrair turistas internacionais. Angola aposta no turismo cultural e ecológico, promovendo a conservação ambiental e o património cultural como pilares estratégicos para o crescimento futuro.

Conclusão | Sem Filtros
A presença de Angola na ITB Berlin 2026 marca um ponto de viragem para o turismo nacional, posicionando o país como um destino inovador e sustentável. A feira destaca Angola não apenas pelas suas paisagens e cultura, mas também pela capacidade de oferecer experiências autênticas e diversificadas, abrindo caminho para se tornar uma potência turística no continente africano.', 'Cultura', 'https://messe-berlinprod-media.e-spirit.cloud/eb9073d7-d515-4782-a31b-1ef49560ea39/itb/bilder/presse/pressemitteilungen/itb-berlin/2026/host-country-itb-berlin-2026_angola_pressreleasecontent.jpg', 'Redacção', false, false, true, 5776, '2026-03-02T14:19:09.278102+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('48f1877d-bcee-49de-834a-d714885903d9', 'Conflito entre Estados Unidos, Israel e Irão ameaça disparar preço do petróleo', 'As tensões no Médio Oriente entre os Estados Unidos, Israel e o Irão podem provocar uma forte subida do preço do petróleo no mercado internacional. Especialistas alertam que, caso o conflito se intensifique, o valor do barril poderá ultrapassar 100 dólares, acima dos actuais 72 dólares, com possíveis impactos na economia mundial e nos países produtores como Angola.', 'O agravamento das tensões no Médio Oriente entre os Estados Unidos, Israel e o Irão tem levantado preocupações nos mercados internacionais de energia. Analistas do sector petrolífero alertam que uma eventual escalada do conflito poderá impulsionar o preço do barril de petróleo para valores superiores a 100 dólares, face aos cerca de 72 dólares registados actualmente nos mercados internacionais.

Especialistas indicam que o Médio Oriente continua a ser uma das regiões mais estratégicas para a produção e exportação de petróleo. Qualquer instabilidade política ou militar pode afectar diretamente o fornecimento global da matéria-prima, provocando reacções imediatas nos mercados financeiros e energéticos.

Um dos principais pontos de preocupação é o Estreito de Ormuz, uma das rotas marítimas mais importantes do mundo para o transporte de petróleo, situado próximo do Irão. Grande parte do petróleo produzido na região passa por esta via, sendo que qualquer bloqueio ou ameaça à sua segurança pode reduzir a oferta global e elevar os preços.

Analistas internacionais defendem que, historicamente, crises geopolíticas no Médio Oriente têm provocado aumentos significativos no preço do petróleo, devido à incerteza quanto à estabilidade da produção e do transporte da commodity.

Caso o preço do barril ultrapasse a marca dos 100 dólares, os efeitos poderão ser sentidos em várias economias do mundo, nomeadamente através do aumento do custo dos combustíveis, da energia e do transporte, factores que tendem a pressionar a inflação global.

Para países produtores como Angola, um aumento do preço do petróleo pode representar um crescimento das receitas provenientes da exportação, uma vez que o crude continua a ser uma das principais fontes de receita da economia nacional.

Contudo, economistas alertam que a volatilidade dos preços no mercado petrolífero exige cautela por parte dos países dependentes deste recurso, defendendo a necessidade de diversificação económica para reduzir a exposição às oscilações do mercado internacional.', 'Economia', 'https://media.istockphoto.com/id/1486726864/fr/photo/baril-de-p%C3%A9trole-et-puits-de-p%C3%A9trole-sur-fond-blanc-avec-pi%C3%A8ce-dor-les-prix-du-p%C3%A9trole.jpg?s=170667a&w=0&k=20&c=03OhT2QMW1SFH0Io4Ym01CpnWgRArnJcwRXF70NjpVQ=', 'Redacção', false, false, true, 5684, '2026-03-02T14:13:49.381282+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('b398a2c1-3f0e-4c88-9e99-5895e07a63d8', 'Novo Presidente de Portugal sinaliza vontade de reforçar cooperação com Angola', 'O novo Presidente português, António José Seguro, manifestou abertura para aprofundar as relações entre Portugal e Angola, logo no dia da sua tomada de posse em Lisboa. Antes do início da cerimónia na Assembleia da República Portuguesa, Seguro dirigiu-se ao Presidente angolano, João Lourenço, com quem manteve uma breve conversa num dos corredores do Parlamento.', 'Embora o conteúdo do diálogo não tenha sido tornado público, ficou evidente a satisfação do novo Chefe de Estado português pela presença de João Lourenço na cerimónia e a intenção de fortalecer os laços históricos entre os dois países. O encontro aconteceu pouco antes de António José Seguro prestar juramento constitucional e assumir formalmente as funções de Presidente da República.

As relações entre Angola e Portugal, formalmente estabelecidas após a independência angolana, mantêm-se como uma das parcerias mais relevantes no espaço lusófono. A cooperação abrange áreas como economia, segurança, educação e investimento, com Portugal a manter-se entre os principais parceiros europeus de Angola.

Deputada luso-angolana vê futuro positivo na cooperação

A deputada luso-angolana Eva Cruzeiro, eleita pelo Partido Socialista, considerou que a chegada de António José Seguro à Presidência poderá fortalecer ainda mais a relação entre os dois países. Em declarações ao Jornal de Angola, a parlamentar descreveu o novo Presidente como uma figura aberta ao diálogo e próxima dos países lusófonos.

Segundo Eva Cruzeiro, os angolanos podem encarar com optimismo o novo ciclo político em Portugal, defendendo que o novo Chefe de Estado deverá dar prioridade à cooperação com os países de língua portuguesa, incluindo Angola.

Sem Filtros (fecho opinativo):
Entre Angola e Portugal, a política muda, mas a ligação mantém-se. Governos passam, presidentes mudam, mas os interesses económicos, a língua comum e a história partilhada continuam a puxar os dois países para a mesma mesa. O desafio agora será transformar boas palavras diplomáticas em cooperação concreta que beneficie realmente os dois povos.', 'Política', 'https://c2a.portais.gov.ao/uploads/large_648288347_1296085185903505_3561954090296633483_n_689a32da53.jpg', 'Redacção', false, false, true, 3673, '2026-03-10T06:47:45.140014+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('afc842f7-cfc1-47c8-86f6-e6e2f855a2f1', 'Relações comerciais: Angola surge na 103.ª posição entre os parceiros de Western Australia em 2025', 'Em 2025, Angola ocupou a 103.ª posição entre os parceiros comerciais de Western Australia, com as trocas bilaterais concentradas sobretudo na exportação de maquinaria pesada destinada à indústria mineira angolana, reforçando a cooperação no sector extractivo.', 'A directora executiva para Parcerias Globais da Investment & Trade Western Australia, Robyn Bobb, afirmou que Angola foi o 103.º parceiro comercial do Estado de Western Australia em 2025, sublinhando que as trocas bilaterais têm incidido, sobretudo, na exportação de maquinaria pesada destinada à indústria mineira angolana. A responsável falava durante um encontro com a Missão Diplomática de Angola naquele Estado australiano, no âmbito do reforço da cooperação económica entre as duas regiões.

De acordo com os dados apresentados, Western Australia lidera o ranking do Produto Interno Bruto entre os estados australianos e é responsável por cerca de 45% do total das exportações da Austrália. A sua economia assenta, maioritariamente, na exploração e transformação de recursos naturais, com destaque para a extracção de minério de ferro, ouro, gás natural liquefeito (LNG) e processamento de lítio, matéria-prima essencial para o fabrico de baterias utilizadas na indústria automóvel.

Impulsionada por esta forte capacidade industrial, a agência estadual de promoção de investimentos conta actualmente com 17 representações internacionais, distribuídas por cidades estratégicas da Europa, Ásia, Médio Oriente e América do Norte, com o objectivo de promover a economia local e estabelecer novas parcerias comerciais.

Perante este cenário, o embaixador de Angola na Austrália, António Luvualu, convidou o sector empresarial de Western Australia a investir em Angola, destacando as oportunidades existentes em diversos sectores da economia nacional, desde a mineração e energia até à agricultura, indústria transformadora e infra-estruturas.

A proposta angolana foi bem acolhida pela Investment & Trade Western Australia, que manifestou interesse e disponibilidade em aprofundar as relações institucionais e empresariais com a congénere angolana, perspectivando o reforço da cooperação económica e a dinamização do intercâmbio comercial entre as duas partes.', 'Economia', 'https://img.freepik.com/premium-photo/beautiful-national-state-flags-australia-angola-together_337817-2413.jpg', 'Redacção', true, false, true, 5263, '2026-03-04T08:00:35.327338+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('78385e5b-105b-4f84-bdf6-89b0f99771c7', 'Justiça à prova: será que o poder está a cercar o Higino Carneiro?', 'Higino Carneiro, antigo general e ex-governador, volta a ser alvo da justiça angolana após anunciar candidatura à liderança do MPLA. Acusado de peculato e burla qualificada, o seu caso levanta suspeitas de “engenharia jurídica” para travar ambições políticas. Mais do que o destino de um dirigente, está em jogo a credibilidade e independência da justiça em Angola.', 'Em maio de 2022, o Tribunal Supremo arquivou processos contra Higino Carneiro, deixando-o livre de julgamento. Na altura, isso parecia marcar o fim de um ciclo judicial que pairava sobre o general. Mas a situação mudou quando Carneiro anunciou publicamente a sua candidatura à liderança do MPLA, colocando-se na corrida à sucessão de João Lourenço.

Pouco depois, a Procuradoria-Geral da República constituiu-o arguido, acusando-o de peculato e burla qualificada, crimes alegadamente cometidos durante os mandatos como governador do Cuando Cubango e de Luanda. No processo 48/20, é acusado de receber mais de 60 viaturas de uma empresa privada, distribuindo-as sem pagamento enquanto governava Luanda.

O momento em que os processos foram reativados levantou suspeitas. Analistas e setores da oposição sugerem que se trata de uma “engenharia jurídica” para travar a candidatura de Carneiro. Mais do que discutir culpabilidade, esta situação expõe um problema estrutural: a fragilidade da confiança pública na independência da justiça angolana.

Num Estado verdadeiramente democrático, a justiça não pode ser instrumento de perseguição política. Quando decisões judiciais coincidem com disputas internas pelo poder, a linha entre legalidade e conveniência política torna-se quase invisível. A confiança das instituições depende tanto da imparcialidade real quanto da percepção pública dessa imparcialidade.

Carneiro reagiu na sua página oficial no Facebook, afirmando: “Nestes processos judiciais, depositamos confiança não como um simples acto de esperança, mas como um compromisso firme com a verdade, com a justiça e com a responsabilidade que nos orienta”. Acrescentou ainda: “Onde existe integridade, existem resultados”. A declaração reforça a sua defesa institucional, mas indica que o embate será judicial e político.

O ponto central, porém, vai além de Higino Carneiro. Está em causa saber se Angola tem uma justiça independente ou se persiste a ideia de que o poder executivo pode influenciar processos. Quando cidadãos — sejam figuras públicas ou anónimos — sentem que a sua posição política os torna alvo de perseguição seletiva, o Estado de Direito enfraquece.

A consolidação democrática exige instituições fortes, autónomas e credíveis. Processos judiciais devem ser conduzidos com rigor técnico, transparência e respeito pelo devido processo legal. Se houver provas, que se julgue; se não houver, que se arquive. O que não pode existir é a sensação de que a justiça funciona ao ritmo das conveniências políticas.

O caso de Higino Carneiro é um teste decisivo para Angola. Mais do que definir o destino de um dirigente, mede a maturidade institucional do país e a credibilidade do sistema judicial. Num momento de renovação de lideranças e aprofundamento democrático, a independência da justiça deve deixar de ser apenas um princípio e tornar-se uma realidade inquestionável.', 'Política', 'https://angola24horas.com/media/k2/items/cache/18c9bdfd9918b498123f3d03e66511f2_XL.jpg', 'Redacção', false, false, true, 7008, '2026-02-23T19:41:37.889827+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('5ed35a0b-7df1-4101-a978-148e543159c5', 'TAAG abre hoje venda de bilhetes para rota Luanda-Abidjan', 'A TAAG Angola Airlines realiza, na tarde desta sexta-feira, numa unidade hoteleira da capital angolana, o lançamento oficial da venda de bilhetes para a nova rota internacional que vai ligar Luanda a Abidjan, na Côte d''Ivoire. A iniciativa marca mais um passo na expansão da rede de destinos da companhia aérea angolana no continente africano.', 'A TAAG Angola Airlines procede, nesta sexta-feira, à abertura oficial das vendas de bilhetes para a nova rota internacional que vai ligar Luanda a Abidjan, na Côte d''Ivoire, num acto que decorre numa das unidades hoteleiras da capital angolana.

A implementação desta rota resulta do Acordo sobre Serviços Aéreos assinado em 2024, em Luanda, entre Angola e a Côte d’Ivoire, instrumento que visa reforçar a cooperação bilateral no sector da aviação civil e promover uma maior integração regional no continente africano.

Considerada uma das principais portas de entrada para a África Ocidental francófona, Abidjan destaca-se como um importante centro financeiro e comercial, recebendo anualmente milhões de visitantes e desempenhando um papel estratégico na dinamização das actividades económicas da região.

De acordo com a transportadora nacional, a nova ligação aérea enquadra-se na estratégia de expansão da TAAG em África, com o objectivo de reforçar a conectividade regional, facilitar a mobilidade de passageiros e estimular as relações comerciais, empresariais e turísticas entre Angola e a Côte d’Ivoire.

O evento de lançamento das vendas de bilhetes deverá contar com a presença de autoridades angolanas e ivoirienses, bem como de representantes do sector da aviação e parceiros institucionais, marcando mais um passo no reforço da presença da TAAG no mercado africano.', 'Economia', 'https://angola24horas.com/media/k2/items/cache/864f245d0a656aa825e14d30ccd5aade_XL.jpg', 'Redacção', true, false, true, 4784, '2026-03-06T09:39:50.266261+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('b33ac629-92b5-45f1-adae-82e1b7c79b02', 'Octávio Capapa: a morte que expõe o esquecimento dos que serviram o Estado', 'A morte de Octávio Capapa, antigo servidor ligado à comunicação e mobilização durante a guerra, levanta críticas sobre o abandono de figuras que dedicaram a vida ao Estado.

O caso reacendeu o debate sobre memória, responsabilidade institucional e apoio a antigos quadros.

Para muitos observadores, o episódio revela uma contradição entre o discurso de reconhecimento histórico e a realidade vivida por alguns veteranos.', 'A morte de Octávio Capapa reacendeu um debate incómodo sobre a forma como Angola trata alguns dos homens que, em diferentes fases da sua história, serviram o Estado e as estruturas políticas dominantes.

Capapa foi durante anos uma figura associada à mobilização política e à comunicação em períodos marcados pela guerra e pela consolidação do poder do MPLA. No entanto, relatos recentes indicam que terá vivido os últimos anos em condições de grande vulnerabilidade social.

A situação ganhou visibilidade pública depois de ser exposta pelo jornalista Jorge Eurico, que chamou atenção para o estado em que Capapa se encontrava. O caso gerou reacções divididas: enquanto alguns criticaram a exposição, outros consideraram que foi a única forma de trazer à luz uma realidade ignorada.

A morte de Capapa reabre um debate mais amplo sobre o destino de muitos quadros que participaram em momentos decisivos da história política do país, mas que, com o passar dos anos, acabam afastados das estruturas de poder e de qualquer rede efectiva de apoio.

Angola Sem Filtros – Análise
O caso de Octávio Capapa tornou-se simbólico porque expõe uma contradição profunda entre o discurso de reconhecimento histórico e a prática institucional.

Em Angola, o sistema político tem mostrado capacidade para recompensar alguns com privilégios duradouros, mas revela fragilidade quando se trata de garantir dignidade mínima a todos os que serviram o Estado.

A morte de Capapa levanta uma pergunta incómoda: quem cuida daqueles que já cumpriram a sua missão e deixaram de ser úteis ao poder? Sem memória institucional e mecanismos de protecção, o país arrisca transformar antigos servidores em nomes esquecidos da sua própria história.', 'Sociedade', 'https://pstzibmplwiatkuanhhn.supabase.co/storage/v1/object/public/news/oj7q7m7ej2_1772820778424.jpg', 'Redacção', true, false, true, 4551, '2026-03-06T18:13:02.606441+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('a10a8b75-8012-412e-9cfb-284ff1ef5f36', 'Preços dos materiais de construção subiram 12% em 2025, mas ritmo de aumento começa a abrandar em Angola', 'Os preços dos materiais de construção em Angola aumentaram em média 12% em 2025, apesar de um abrandamento gradual registado nos últimos meses do ano. De acordo com dados do Instituto Nacional de Estatística, o Índice de Preços dos Materiais de Construção (IPMC) caiu 0,9 pontos percentuais em Dezembro face a Novembro, atingindo a taxa homóloga mais baixa dos últimos 28 meses.', 'Apesar da desaceleração, os preços continuam a subir e a pressionar o custo da construção no país. Materiais como blocos, vigas, tijolos e aço registaram as maiores variações anuais, com aumentos superiores a 17%. Especialistas alertam que a ausência de uma indústria nacional robusta de materiais de construção e a fraca fiscalização de preços têm contribuído para a escalada dos custos no sector.

Um dos casos mais polémicos continua a ser o cimento. Nos últimos meses de 2025, o produto chegou a ser vendido no mercado informal por mais de 10 mil kwanzas o saco, valor muito superior ao praticado à porta das fábricas. Ainda assim, o relatório do INE aponta uma variação mensal mínima para o cimento em Dezembro, o que tem levantado dúvidas entre analistas sobre os métodos de recolha e classificação de preços utilizados nas estatísticas oficiais.

Sem Filtros (fecho opinativo):
Quando o preço dos materiais dispara, o sonho da casa própria afasta-se ainda mais da maioria das famílias. Entre especulação no mercado, fraca fiscalização e dependência de importações, construir em Angola continua a ser um luxo. Enquanto o sector não ganhar base industrial sólida, o cimento e o ferro continuarão a pesar tanto no orçamento quanto nas paredes das casas. 🏗️', 'Economia', 'https://estamosjuntos.co.ao/wp-content/uploads/2025/07/Construcao-civil-Angola.jpg', 'Redacção', false, false, true, 3201, '2026-03-12T06:26:41.375562+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('f0cecef2-1b7d-4fdb-8e5a-d7fc3a99bb2e', 'Irão ameaça fechar Estreito de Ormuz e alerta para petróleo a 200 dólares', 'A guerra no Médio Oriente entrou no 12.º dia de confrontos intensos, com o Irão a atacar pelo menos três navios mercantes no Golfo Pérsico para reforçar a ameaça de bloqueio do estratégico Estreito de Ormuz. O porta-voz militar iraniano, Ebrahim Zolfaqari, avisou que o preço do petróleo pode disparar para 200 dólares por barril caso a instabilidade na região continue.', 'Segundo relatos da imprensa internacional, pelo menos um dos cargueiros atingidos — de bandeira tailandesa — teve de ser evacuado após um incêndio a bordo próximo de Omã. Outros navios afectados foram conduzidos para portos dos Emirados Árabes Unidos. No mesmo período, os Estados Unidos anunciaram ter destruído 16 embarcações iranianas utilizadas para lançar minas marítimas, numa tentativa de manter aberta a rota energética mais importante do planeta.

Cerca de 20% do petróleo e do gás natural liquefeito transportado por via marítima no mundo passa pelo Estreito de Ormuz. A escalada militar já provocou forte volatilidade no mercado energético, com o barril de referência Brent crude oil a oscilar acima dos 90 dólares depois de ter chegado perto dos 120. No terreno, os confrontos também envolveram ataques a infra-estruturas e posições militares ligadas a aliados de Teerão, incluindo o Hezbollah.

Sem Filtros (fecho opinativo):
Quando o Estreito de Ormuz entra na linha de fogo, o impacto deixa de ser apenas regional — torna-se global. O petróleo é a artéria da economia mundial, e qualquer ameaça a essa rota transforma um conflito militar numa crise energética capaz de abalar governos, mercados e consumidores em todo o planeta. 🌍⛽', 'Economia', 'https://pstzibmplwiatkuanhhn.supabase.co/storage/v1/object/public/news/hklcuo15x17_1773298246455.jpg', 'Redacção', true, false, true, 3257, '2026-03-12T06:50:52.208106+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('a9c5093c-5f4a-47d0-8a71-60dd009b8e3b', 'Mercado petrolífero: Brent crude oil toca os 80 dólares', 'O barril de Brent crude oil, referência para as exportações de Angola, foi negociado ontem no mercado de futuros de Londres entre 75,30 e 80,20 dólares, reflectindo oscilações ao longo da sessão.', 'Preço do barril do Brent “bate” nos 80 dólares

O preço do barril de petróleo da referência internacional Brent crude oil atingiu, esta semana, a marca dos 80 dólares, impulsionado por factores ligados às tensões geopolíticas, cortes na produção e expectativas em torno da procura global de energia.

Nos mercados internacionais, o aumento do Brent reflecte a sensibilidade dos investidores a riscos associados ao fornecimento, particularmente em regiões estratégicas produtoras de petróleo. Analistas indicam que qualquer instabilidade nas cadeias de abastecimento tende a provocar reacções imediatas nos preços, dada a importância do crude para a economia mundial.

Além das questões geopolíticas, decisões da OPEP e seus aliados relativamente aos níveis de produção continuam a influenciar directamente o comportamento do mercado. A gestão da oferta, aliada à recuperação gradual da procura em várias economias, tem contribuído para sustentar a valorização da matéria-prima.

Para Angola, país produtor e membro da OPEP, a subida do preço do Brent representa um potencial reforço das receitas fiscais e cambiais, num contexto em que o petróleo continua a desempenhar papel determinante no Orçamento Geral do Estado e na balança comercial.

Economistas, no entanto, alertam para a volatilidade do mercado petrolífero, sublinhando que oscilações bruscas podem ocorrer em função de factores externos, como decisões políticas, evolução da economia global e alterações na oferta internacional.

A manutenção do Brent em torno dos 80 dólares poderá trazer maior previsibilidade às contas públicas, mas especialistas defendem prudência e continuidade dos esforços de diversificação económica para reduzir a dependência do sector petrolífero.', 'Economia', 'https://angola24horas.com/media/k2/items/cache/c469bafeb90b97ef9b267e00b4aff073_XL.jpg', 'Redacção', false, false, true, 5517, '2026-03-03T11:19:46.137282+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('3709dac3-4cbb-4151-be49-48c3ae5635d7', 'Falta de investimentos trava crescimento de Icolo e Bengo', 'A província de Icolo e Bengo necessita de novos investimentos para impulsionar o sector dos recursos minerais, petróleo e gás, segundo um relatório divulgado pela Agência Nacional de Recursos Minerais (ANRM). O documento, tornado público na quinta-feira, analisa a situação dos títulos mineiros na região e aponta a necessidade de maior dinamização do sector para potenciar o desenvolvimento económico local.', 'apesar do potencial geológico identificado na província, ainda há necessidade de maior participação de investidores e operadores do sector para impulsionar projectos de prospecção, pesquisa e exploração de recursos minerais. Segundo a ANRM, a mobilização de capital e tecnologia é fundamental para transformar esse potencial em projectos produtivos capazes de gerar impacto económico.

De acordo com o relatório, o desenvolvimento do sector extractivo em Icolo e Bengo pode desempenhar um papel relevante na diversificação da economia local, contribuindo para o aumento da produção mineral, criação de postos de trabalho e dinamização de cadeias de valor associadas à actividade mineira.

A agência reguladora sublinha ainda que o reforço de investimentos permitirá melhorar o aproveitamento dos títulos mineiros já atribuídos, bem como incentivar a realização de novos estudos geológicos e a identificação de outras áreas com potencial de exploração.

Especialistas do sector defendem que, para tornar a província mais atractiva aos investidores, será igualmente importante reforçar as infra-estruturas de apoio à actividade mineira, como estradas, energia e logística, factores considerados essenciais para viabilizar projectos de exploração em grande escala.

Com estas medidas, a expectativa é que Icolo e Bengo possa afirmar-se gradualmente como uma das regiões com maior potencial para o desenvolvimento do sector mineiro em Angola, contribuindo para o crescimento económico regional e para o fortalecimento da indústria extractiva nacional.', 'Economia', 'https://rna.ao/rna.ao/wp-content/uploads/2026/01/IMG_8895-770x544.jpeg', 'Redacção', false, false, true, 4845, '2026-03-06T09:56:25.228458+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('172cfaf7-af9b-4aac-a241-ac496762a8da', 'Transferência das operações para Aeroporto António Agostinho neto concluída', 'O processo de transferência das operações regulares de passageiros do Aeroporto Internacional 4 de Fevereiro para o Aeroporto Internacional Dr. António Agostinho Neto (AIAAN), na província de Icolo e Bengo, está oficialmente concluído.', 'Iniciado a 10 de Novembro de 2024, a conclusão do processo foi assinalada este domingo, 1 de Março deste ano, com o início das operações da Airlink, segundo um comunicado de imprensa enviado ao Jornal de Angola Online.

O primeiro voo da companhia sul-africana aterrou no AIAAN às 12h20, transportando 80 passageiros a bordo de uma aeronave Embraer 190.

Com sede em Joanesburgo, a Airlink assegura ligações entre Angola e a África do Sul desde 21 de Outubro de 2021.

A partir de agora, a transportadora passa a realizar quatro frequências semanais, estabelecendo a ligação entre o Aeroporto Internacional Oliver Tambo, em Joanesburgo, e o Aeroporto Internacional Dr. António Agostinho Neto, localizado na província do Icolo e Bengo.
', 'Sociedade', 'https://www.opais.ao/wp-content/uploads/2026/03/efd470c605fbb2041112f655ad006d11_XL.webp', 'Redacção', false, false, true, 5914, '2026-03-01T21:00:28.691606+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('cf2562d4-2e05-4929-affa-ec1d63fc34a3', 'Senegal desafia CAF e recusa devolver troféu da CAN em meio a acusações de corrupção', 'A Federação Senegalesa de Futebol recusa-se a devolver o troféu da CAN após decisão polémica da CAF que atribui o título a Marrocos. O caso pode seguir para o Tribunal Arbitral do Desporto.', 'A Federação Senegalesa de Futebol rejeitou devolver o troféu da Taça das Nações Africanas, após a Confederação Africana de Futebol ter retirado o título ao Senegal e atribuído uma vitória administrativa por 3-0 a Marrocos, 58 dias depois da final disputada em campo.

A decisão, considerada inédita, gerou forte reacção por parte da federação senegalesa, que acusa a CAF de corrupção e promete levar o caso ao Tribunal Arbitral do Desporto, na Suíça, para contestar a legalidade da medida.

O título havia sido conquistado pelo Senegal dentro das quatro linhas, o que agrava ainda mais a polémica em torno da decisão administrativa que reverte o resultado desportivo.

Análise – Angola Sem Filtros

Se isto se confirmar, não é apenas uma polémica —
é um abalo sério na credibilidade do futebol africano.

Retirar um título quase dois meses depois da final é uma decisão extrema e levanta questões pesadas:

o que aconteceu de tão grave para justificar isso?

por que não foi resolvido antes?

quem ganha com esta reviravolta?

A reacção do Senegal não é só emocional — é estratégica. Ao levar o caso ao TAD, mostra que não aceita uma decisão que considera política e não desportiva.

No meio disso tudo, fica uma imagem perigosa:
a de que títulos em África podem ser decididos fora do campo.

E quando isso acontece, o futebol perde a sua base mais importante:
a confiança.', 'Desporto', 'https://res.feednews.com/assets/v2/99b6ae7ee31eaa3c43647187c259be02?quality=uhq&resize=720&cl=ao_pt', 'Redacção', false, false, true, 1549, '2026-03-18T17:44:24.85294+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('2ab67af4-afc7-49b8-bbbe-14590aa265da', 'Antigos combatentes aplaudem programa de habitação social anunciado por João Lourenço', 'Delegações provinciais de antigos combatentes manifestaram apoio à iniciativa do Presidente da Angola, João Lourenço, que autorizou a construção de habitações sociais destinadas a antigos combatentes portadores de deficiência. O programa deverá beneficiar cidadãos nas províncias do Icolo e Bengo, Bengo, Bié, Moxico e Cuando Cubango.', 'Segundo representantes das delegações provinciais, a decisão é vista como um passo importante para reduzir as dificuldades sociais enfrentadas por muitos antigos combatentes, sobretudo aqueles que vivem com limitações físicas resultantes da sua participação em momentos marcantes da história do país.

Os antigos combatentes consideram que o programa de habitação representa também um reconhecimento do contributo dado por milhares de cidadãos na luta pela independência e na defesa da soberania nacional, esperando que a medida traga melhorias concretas nas condições de vida dos beneficiários.

Sem Filtros (fecho opinativo):
Durante décadas, muitos antigos combatentes viveram entre promessas e dificuldades. Programas como este mostram reconhecimento, mas o verdadeiro desafio será garantir que as casas saiam do papel e cheguem efectivamente a quem mais precisa. Em Angola, a diferença entre anúncio e realidade ainda é um teste constante às políticas públicas. 🇦🇴🏠', 'Sociedade', 'https://pstzibmplwiatkuanhhn.supabase.co/storage/v1/object/public/news/o45nuf6xgy_1773297129988.jpg', 'Redacção', false, false, true, 3186, '2026-03-12T06:32:27.304702+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('e257c749-705d-4077-a5b9-3f37b3dadc31', 'Isabel dos Santos alerta para retrocesso na produção de cimento em Angola', '“Angola voltou a importar cimento depois de quase 10 anos. Antes, o cimento produzido a nível nacional era suficiente”, afirmou.', 'A empresária angolana Isabel dos Santos manifestou preocupação com a retoma das importações de cimento em Angola, após quase dez anos em que a produção nacional satisfazia a procura interna.

Em declarações nos stories do seu perfil no Instagram, Isabel dos Santos considerou preocupante que o país volte a depender do mercado externo para suprir as necessidades do sector da construção civil.

Durante o período de maior estabilidade industrial, investimentos significativos na indústria cimenteira permitiram reduzir importações, fortalecer a cadeia de valor da construção e dinamizar o emprego. Para a empresária, a decisão atual representa um sinal de enfraquecimento da capacidade produtiva interna.', 'Economia', 'https://imagens.publico.pt/imagens.aspx/1756145?tp=UH&db=IMAGENS&type=JPG', 'Redacção', true, false, true, 7090, '2026-02-23T20:08:22.34507+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('525ac056-4580-49e8-a957-b2d91a0b480e', 'Ministério da Saúde inicia certificação de médicos especialistas a 26 deste mês', 'O Ministério da Saúde de Angola começa a entrega de certificados aos médicos especialistas formados no âmbito do Projecto de Recursos Humanos em Saúde, consolidando competências e reforçando a capacidade técnica do Sistema Nacional de Saúde.', 'O Ministério da Saúde dará início, a partir de 26 de fevereiro, à cerimónia oficial de certificação dos médicos especialistas formados pelo Projecto de Recursos Humanos em Saúde. A iniciativa foi orientada pela ministra Sílvia Lutucuta e pretende formalizar o reconhecimento institucional do esforço e dedicação dos profissionais do setor.

Nesta segunda-feira, 23, decorreu no Instituto de Especialização em Saúde (IES) um encontro técnico de concertação para harmonizar e validar todos os procedimentos logísticos e institucionais da certificação. O evento contou com a presença do coordenador do projeto, Job Monteiro, do director-adjunto do IES, Eduardo Caiangula, membros da Direcção da Unidade de Implementação do Projecto (UIP) e representantes do Gabinete de Comunicação Institucional do MINSA.

Segundo Job Monteiro, a maioria dos especialistas concluiu a formação no último trimestre de 2025, enquanto outros finalizaram em janeiro deste ano. Todas as condições técnicas foram consideradas reunidas para o acto de certificação, considerado um momento de reconhecimento da competência dos quadros nacionais.

A ministra Sílvia Lutucuta destacou que a valorização dos especialistas é um compromisso estratégico do Executivo, essencial para garantir a qualidade, humanização e eficiência dos serviços de saúde. A iniciativa reafirma o empenho do Governo de Angola em modernizar e fortalecer o Sistema Nacional de Saúde, alinhando formação, reconhecimento e prática profissional.

Rodapé editorial (Sem Filtros)

Nota do editor: A certificação de especialistas médicos reforça a capacidade técnica do Sistema Nacional de Saúde e evidencia a prioridade do Governo na formação contínua de profissionais qualificados. Acompanhar de perto estas iniciativas é essencial para compreender o desenvolvimento do setor em Angola.', 'Saúde', 'https://i0.wp.com/focosaude.ao/wp-content/uploads/2025/10/561562967_1419572563062644_3390076942174619315_n.jpg?resize=1024%2C768&ssl=1', 'Redacção', false, false, true, 7128, '2026-02-25T02:19:14.266299+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('591edccc-6d60-47b1-8f17-ab6851f9a5c8', '📰 Moçambique contrata consultora dos EUA após críticas do FMI e gera debate interno', 'Depois das críticas do Fundo Monetário Internacional à situação económica de Moçambique, o Governo decidiu contratar a consultora norte-americana Alvarez & Marsal para apoiar a reorganização das contas públicas. A decisão está a gerar contestação entre especialistas, que questionam os custos e a necessidade de recorrer a apoio externo quando existem quadros nacionais qualificados.', 'A contratação de uma consultora internacional pelo Governo moçambicano surge na sequência de alertas do Fundo Monetário Internacional sobre a fragilidade do ambiente macroeconómico do país. Entre as principais preocupações estão o crescimento moderado, a redução da ajuda externa, a vulnerabilidade fiscal e o aumento da dívida interna.

O Ministério das Finanças anunciou a contratação da empresa norte-americana especializada em reestruturação e revitalização de instituições em crise, com o objectivo de apoiar o Executivo a reorganizar as contas públicas e melhorar a gestão financeira do Estado.

A medida, porém, gerou debate no meio académico e económico. A economista Teresa Boene questiona a necessidade de recorrer a especialistas estrangeiros, defendendo que Moçambique possui profissionais qualificados nas áreas de economia e finanças capazes de apoiar reformas fiscais.

Outra preocupação levantada prende-se com o custo da consultoria e o chamado custo de oportunidade — isto é, quanto o Estado irá gastar e que benefícios concretos poderá obter em comparação com outras prioridades de investimento público.

O FMI, por sua vez, recomenda contenção salarial e reformas estruturais para restaurar a estabilidade macroeconómica, proteger grupos vulneráveis e criar bases para um crescimento sustentável e inclusivo.

Já o analista Anísio Buanaissa defende uma abordagem alternativa, argumentando que o aumento da procura interna e a valorização da produção nacional podem dinamizar a economia, estimular o investimento privado e contribuir para maior arrecadação fiscal.

O debate evidencia um dilema recorrente em economias em desenvolvimento: equilibrar apoio técnico internacional com o aproveitamento da capacidade interna, garantindo ao mesmo tempo transparência, eficiência e resultados concretos para a população.', 'Mundo', 'https://odestaque.co.mz/wp-content/uploads/2025/10/Presidente-da-Republica-visita-a-sede-do-FMI-em-Washington-D.C-9-1-e1761659988717.jpeg', 'Redacção', false, false, true, 7002, '2026-02-24T11:49:34.524597+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('772f4887-02c5-415c-844c-3d22f5c94a34', 'Sem Filtros | RDCongo: Governo e M23 trocam acusações de violação do cessar-fogo mediado por Angola', 'O Governo da República Democrática do Congo e o grupo armado Movimento 23 de Março (M23) acusaram-se mutuamente de violar o cessar-fogo proposto por Angola para o leste da RDCongo.', 'O contexto

Angola propôs que o cessar-fogo entrasse em vigor na quarta-feira.

Kinshasa aceitou a proposta, mas sem confirmar uma data específica.

O M23 reagiu acusando o Governo de manipulação e alegou que o cessar-fogo já teria sido violado.

O leste da RDCongo enfrenta mais de 30 anos de conflitos contínuos. Desde 2021, o M23 ressurgiu, retomando vastas áreas nos Kivu do Norte e Kivu do Sul, com alegado apoio do Ruanda. Em dezembro, o grupo lançou uma ofensiva contra Uvira, mesmo durante negociações entre RDCongo e Ruanda sob mediação norte-americana, irritando Washington.

O quadro atual

A intensidade dos combates diminuiu temporariamente na quarta e quinta-feira, segundo fontes locais.

Hoje, o exército congolês acusou o M23 de atacar posições em Kivu do Norte e Kivu do Sul, afirmando que o grupo sabotou o processo de paz.

O M23 denunciou, por sua vez, violações do cessar-fogo pelas forças de Kinshasa.

Fontes locais indicam retoma dos combates nos arredores de Minembwe, planaltos do Kivu do Sul, onde o exército congolês, apoiado por milícias locais e soldados burundeses, enfrenta milícias alinhadas ao M23. Nos restantes pontos da frente, a calma relativa foi mantida.

Leitura crítica (Sem Filtros)

A situação demonstra a fragilidade das mediações externas: mesmo com Angola e os EUA a tentar impor cessar-fogo, a desconfiança mútua e a pressão militar imediata tornam qualquer acordo temporário e volátil.

A escalada em Minembwe evidencia que linhas de frente locais continuam a ser palco de confrontos, independentemente dos anúncios formais de cessar-fogo.

A narrativa oficial de ambos os lados é de acusação mútua, enquanto o terreno mostra que o conflito é estrutural e resistente a acordos pontuais, indicando que qualquer trégua terá de ser acompanhada de fiscalização real e comprometimento militar concreto.', 'Política', 'https://s.rfi.fr/media/display/7ac5757a-6a80-11ed-9491-005056bfb2b6/w:1280/p:16x9/REUTERS%20-%20James%20Akena.png', 'Redacção', true, true, true, 7160, '2026-02-25T01:18:22.933063+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('b901ef67-a68f-42d3-b02e-e7ca0210b26a', 'João Lourenço troca liderança na PGR e nomeia Pedro Mendes de Carvalho', 'O Presidente da República nomeou Pedro Mendes de Carvalho como novo procurador-geral da República, substituindo Hélder Pita Grós, após validação do processo pelo órgão competente.', 'O Presidente João Lourenço nomeou, esta quarta-feira (18), Pedro Mendes de Carvalho para o cargo de procurador-geral da República, marcando o fim do mandato de Hélder Pita Grós.

A nomeação acontece após a homologação dos resultados da eleição dos candidatos pelo Conselho Superior da Magistratura do Ministério Público, órgão responsável pela condução do processo.

A decisão foi formalizada na 4.ª sessão extraordinária do órgão, referente ao 4.º ano do 5.º mandato, realizada no passado dia 16 de Março de 2026.

Análise – Angola Sem Filtros

Mudam-se os nomes, mas a grande questão mantém-se:
vai mudar alguma coisa na justiça angolana?

A saída de Hélder Pita Grós encerra um ciclo marcado por forte mediatização do combate à corrupção, mas também por críticas quanto à selectividade dos processos e aos resultados práticos.

A entrada de Pedro Mendes de Carvalho levanta expectativas, mas também desconfiança:

haverá continuidade ou ruptura?

o Ministério Público ganhará mais independência real ou manterá alinhamento político?

Num país onde a justiça é frequentemente vista como instrumento e não como árbitro, o novo procurador-geral entra com um desafio claro:
provar, com actos — não discursos — que a lei é igual para todos.', 'Sociedade', 'https://www.vozdeangola.com/media/k2/items/cache/bd29c45aa603ee6a2c9d275e0264c267_M.jpg', 'Redacção', false, false, true, 1417, '2026-03-18T17:36:16.065234+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('e50be5a3-1b60-40e0-958e-d3d8432002ff', 'Angolanos retirados de Israel chegam a Luanda após operação de evacuação marcada por tensão no Médio Oriente', 'O Governo angolano concluiu a segunda fase da operação de retirada de cidadãos nacionais que se encontravam em Israel, num contexto de crescente tensão militar no Médio Oriente. Oito angolanos chegaram esta sexta-feira a Luanda depois de vários dias de incerteza, numa operação organizada pelo Ministério das Relações Exteriores para garantir a segurança dos compatriotas.', 'Segundo o embaixador de Angola em Israel, Nelson Cosme, esta etapa do plano de contingência envolveu uma longa deslocação terrestre de mais de dez horas entre Telavive e o Cairo, no Egipto, antes do embarque aéreo com escala em Adis Abeba, na Etiópia, até Luanda. Na primeira fase da operação, realizada na semana passada, já tinham sido retirados nove cidadãos.

As autoridades angolanas indicam que, para já, não está prevista uma terceira evacuação. Parte dos angolanos que continuam em Israel são religiosos ou têm vínculos familiares no país e optaram por permanecer. No total, as duas fases da operação permitiram o regresso a Angola de 22 cidadãos, num momento em que o conflito regional se intensifica após ataques e retaliações militares envolvendo Israel, Irão e os Estados Unidos.

Sem Filtros (fecho opinativo):
A evacuação mostra que, quando há vontade política, o Estado consegue proteger os seus cidadãos no exterior. Mas também expõe uma realidade: milhares de angolanos vivem e trabalham em zonas de risco no mundo, muitas vezes longe da atenção do próprio país. Em tempos de crise internacional, a diplomacia deixa de ser protocolo e passa a ser, simplesmente, uma questão de salvar vidas.', 'Sociedade', 'https://kiami-ja-back.kiamisoft.ao/cms/Infrastructure/Files/Repositorio/Imagens/6271645_imagem.jpeg', 'Redacção', false, false, true, 3893, '2026-03-09T17:40:33.724165+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('66cb7e74-0658-44f8-84cb-9e09f0c5cd62', 'Irão condiciona passagem no Estreito de Ormuz à expulsão de diplomatas dos Estados Unidos e de Israel', 'A Guarda Revolucionária Islâmica anunciou que permitirá passagem livre pelo Estreito de Ormuz apenas a navios provenientes de países árabes ou europeus que decidam expulsar diplomatas dos Estados Unidos e de Israel. A declaração surge num momento de forte escalada política e militar na região do Golfo.', 'O estreito de Ormuz é considerado um dos corredores marítimos mais estratégicos do mundo, por onde passa cerca de 20 por cento do comércio global de petróleo. Actualmente, a região enfrenta um bloqueio quase total, depois de ameaças das forças iranianas contra qualquer embarcação que tente atravessar a zona sem autorização.

Segundo a imprensa internacional, o impacto da medida já se faz sentir nos mercados energéticos globais. O preço do barril de petróleo ultrapassou os 100 dólares, reflexo directo da crescente tensão geopolítica no Médio Oriente e do receio de interrupções no fornecimento mundial de energia.

Sem Filtros (fecho opinativo):
Quando o petróleo entra na equação, a política internacional torna-se ainda mais explosiva. O Estreito de Ormuz não é apenas uma rota marítima — é uma peça-chave da economia mundial. Qualquer ameaça ao seu funcionamento transforma-se imediatamente num problema global, capaz de afectar desde governos até o bolso de milhões de consumidores. 🌍⛽', 'Mundo', 'https://images.impresa.pt/expresso/2026-03-04-irao-estreito-ormuz.jpg-4f92e271/16x9/mw-1200&outputFormat=jpeg', 'Redacção', false, false, true, 3354, '2026-03-11T10:44:24.41516+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
INSERT INTO public.news_articles (id, title, summary, content, category, image_url, author, is_hero, is_breaking, published, views, created_at, updated_at) VALUES ('5878c5af-444e-4448-9132-9e44d6a39fc6', 'Escolha do novo líder supremo do Irão provoca irritação em Washington e reacção de Trump', 'A nomeação de Mojtaba Khamenei como novo Líder Supremo do Irão gerou desconforto em Washington. O Presidente dos Estados Unidos, Donald Trump, manifestou esta segunda-feira desagrado pela escolha, que sucede ao longo domínio do aiatolá Ali Khamenei, numa transição que pode agravar a tensão entre Irão e Estados Unidos.', 'Questionado sobre a possibilidade de uma intervenção militar norte-americana, Trump afirmou que não existe qualquer decisão nesse sentido e que Washington está “longe de avançar” para o envio de tropas para território iraniano. A reacção surge num momento de forte instabilidade regional e de escalada de confrontos indirectos entre potências no Médio Oriente.

Considerado próximo da Guarda Revolucionária Islâmica, Mojtaba Khamenei é visto por analistas como defensor de uma linha conservadora semelhante à seguida pelo pai. Especialistas em relações internacionais alertam que a sucessão, formalmente supervisionada pela Assembleia de Peritos, poderá endurecer ainda mais a postura de Teerão perante a pressão externa de Washington e de aliados como Israel.

Sem Filtros (fecho opinativo):
No Irão, o poder raramente muda de rumo — muda apenas de mãos. A irritação de Washington revela mais frustração estratégica do que surpresa política. O verdadeiro problema não é quem lidera em Teerão, mas o facto de o confronto entre as duas potências continuar preso a um ciclo de desconfiança que mantém o Médio Oriente permanentemente à beira da explosão.', 'Mundo', 'https://cdn.folhape.com.br/upload/dn_arquivo/2026/03/afp-20260303-99nn9g4-v2-midres-topshotusiranisraelwartrump.jpg', 'Redacção', false, true, true, 3879, '2026-03-09T19:25:50.730123+00:00', '2026-03-24T08:30:00.184503+00:00') ON CONFLICT DO NOTHING;
